default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

 host: localhost
 username: postgres
 password: 1234

development:
 <<: *default
 database: bugzilla_development

test:
 <<: *default
 database: bugzilla_test

production:
 <<: *default
 database: bugzilla_production
 username: postgres
 password: <%= ENV['BUGZILLA_DATABASE_PASSWORD'] %>